task_manager/labels/urls.py
from django.urls import path

from .views import (
    CreateLabelsView,
    DeleteLabelsView,
    IndexLabelsView,
    UpdateLabelsView,
)

app_name = 'labels'

urlpatterns = [
    path("", IndexLabelsView.as_view(), name="index"),
    path("create/", CreateLabelsView.as_view(), name="create"),
    path("<int:pk>/update/", UpdateLabelsView.as_view(), name="update"),
    path("<int:pk>/delete/", DeleteLabelsView.as_view(), name="delete"),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks.views import (
    CreateTaskView,
    DeleteTaskView,
    IndexTaskView,
    ShowTaskView,
    UpdateTaskView,
)

app_name = "tasks"

urlpatterns = [
    path("", IndexTaskView.as_view(), name="index"),
    path("create/", CreateTaskView.as_view(), name="create"),
    path("<int:pk>/update/", UpdateTaskView.as_view(), name="update"),
    path("<int:pk>/delete/", DeleteTaskView.as_view(), name="delete"),
    path("<int:pk>/", ShowTaskView.as_view(), name="show"),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import IndexView, LoginView, LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("users/", include("task_manager.users.urls")), 
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("statuses/", include("task_manager.statuses.urls")),
    path('tasks/', include('task_manager.tasks.urls')),
    path("labels/", include("task_manager.labels.urls")),
   ]
    

task_manager/users/urls.py
from django.urls import path

from task_manager.users.views import (
    CreateUserView,
    DeleteUserView,
    IndexUserView,
    UpdateUserView,
)

app_name = "users"

urlpatterns = [
    path("", IndexUserView.as_view(), name="index"),
    path("create/", CreateUserView.as_view(), name="create"),
    path("<int:pk>/update/", UpdateUserView.as_view(), name="update"),
    path("<int:pk>/delete/", DeleteUserView.as_view(), name="delete"),
]

task_manager/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class LoginForm(forms.Form):
    username = forms.CharField(
        label=_("Username"),
        max_length=150,
        required=True,
        widget=forms.TextInput(),
    )
    password = forms.CharField(
        label=_("Password"), widget=forms.PasswordInput(), required=True
    )

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label


class CreateLabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ["name"]
        labels = {"name": _("Name")}

    def clean_name(self):
        label_name = self.cleaned_data["name"]
        label = Label.objects.filter(name=label_name)

        if label.exists() and self.instance.pk != label[0].pk:
            raise forms.ValidationError(
                _("Label with this name already exists.")
            )
        return label_name

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from task_manager.labels.forms import CreateLabelForm
from task_manager.labels.models import Label
from task_manager.tasks.models import Task


class BaseLabelsView(LoginRequiredMixin, View):
    login_url = reverse_lazy("login")
    redirect_field_name = None

    def handle_no_permission(self):
        messages.error(
            self.request,
      
            _("You are not logged in! Please sign in.")
            )
        return super().handle_no_permission()


class IndexLabelsView(BaseLabelsView):
    def get(self, request):
        labels = Label.objects.all()
        return render(request, "labels/index.html", context={"labels": labels})


class CreateLabelsView(BaseLabelsView):
    def get(self, request):
        form = CreateLabelForm()
        return render(request, "labels/create.html", context={"form": form})

    def post(self, request):
        form = CreateLabelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _("Label successfully created"))
            return redirect("labels:index")
        return render(request, "labels/create.html", context={"form": form})


class UpdateLabelsView(BaseLabelsView):
    def get(self, request, pk):
        label = get_object_or_404(Label, pk=pk)
        form = CreateLabelForm(instance=label)
        return render(
            request,
            "labels/update.html",
            {
                "form": form, 
                "label": label
            }
            )

    def post(self, request, pk):
        label = get_object_or_404(Label, pk=pk)
        form = CreateLabelForm(request.POST, instance=label)
        if form.is_valid():
            form.save()
            messages.success(request, _("Label successfully updated"))
            return redirect("labels:index")
        return render(
            request,
            "labels/update.html",
            {
                "form": form,
                "label": label
            }
            )


class DeleteLabelsView(BaseLabelsView):
    def get(self, request, pk):
        label = get_object_or_404(Label, pk=pk)
        return render(request, "labels/delete.html", {"label": label})

    def post(self, request, pk):
        label = get_object_or_404(Label, pk=pk)
        if Task.objects.filter(labels=label).exists():
            messages.error(
                request, _("Cannot delete label because it is in use")
            )
            return redirect("labels:index")
        label.delete()
        messages.success(request, _("Label successfully deleted"))
        return redirect("labels:index")

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import ListView
from task_manager.tasks.models import Task
from django.views.generic.edit import CreateView, UpdateView
from .forms import CreateStatusForm
from .models import Status


class BaseStatusView(LoginRequiredMixin, View):
    login_url = reverse_lazy("login")
    redirect_field_name = None

    def handle_no_permission(self):
        messages.error(
            self.request, 
            _("You are not logged in! Please sign in")
            )
        return super().handle_no_permission()


class IndexStatusesView(BaseStatusView, ListView):
    model = Status
    template_name = "statuses/index.html"
    context_object_name = "statuses"
    ordering = ["id"]


class CreateStatusesView(BaseStatusView, CreateView):
    model = Status
    form_class = CreateStatusForm
    template_name = "statuses/create.html"
    success_url = reverse_lazy("statuses:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Status successfully created"))
        return response


class UpdateStatusesView(BaseStatusView, UpdateView):
    model = Status
    form_class = CreateStatusForm
    template_name = "statuses/update.html"
    success_url = reverse_lazy("statuses:index")
    context_object_name = "status"

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Status successfully updated"))
        return response


class DeleteStatusesView(BaseStatusView):
    def get(self, request, pk):
        status = Status.objects.get(pk=pk)
        return render(
            request,
            "statuses/delete.html",
            context={
                "status": status,
            },
        )

    def post(self, request, pk):
        status = get_object_or_404(Status, pk=pk)
        if Task.objects.filter(status=status).exists():
            messages.error(
                request, _("Cannot delete status because it is in use")
            )
            return redirect("statuses:index")
        status.delete()
        messages.success(request, _("Status successfully deleted"))
        return redirect("statuses:index")

task_manager/tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import CreateTaskForm
from .models import Task
from django.shortcuts import get_object_or_404
from task_manager.tasks.filters import TaskFilter
from django.urls import reverse


class BaseTaskView(LoginRequiredMixin, View):
    login_url = reverse_lazy("login")
    template_name = None


class CreateTaskView(BaseTaskView):
    template_name = "tasks/create.html"
    form_class = CreateTaskForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = request.user
            task.save()
            form.save_m2m()  
            messages.success(request, _("Task successfully created"))
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            print(form.errors)  
        return render(request, self.template_name, {"form": form})


class IndexTaskView(BaseTaskView):
    def get(self, request):
        tasks = Task.objects.all()
        filterset = TaskFilter(request.GET, queryset=tasks, request=request)
        return render(
            request,
            "tasks/index.html",
            context={
                "form": filterset.form,
                "tasks": filterset.qs,
            },
        )


class DeleteTaskView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        """Проверка, что пользователь — автор задачи, до любого метода."""
        self.task = get_object_or_404(Task, pk=kwargs["pk"])
        if self.task.author != request.user:
            messages.error(request, 
                           _("A task can only be deleted by its author.")
                           )
            return redirect("tasks:index")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "tasks/delete.html",
            context={"task": self.task},
        )

    def post(self, request, *args, **kwargs):
        self.task.delete()
        messages.success(request, _("Task successfully deleted"))
        return redirect("tasks:index")


class UpdateTaskView(BaseTaskView):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        return self._render_form(request, CreateTaskForm(instance=task), task)

    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        form = CreateTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request, _("Task successfully updated"))
            return redirect("tasks:index")
        return self._render_form(request, form, task)

    def _render_form(self, request, form, task):
        return render(
            request, "tasks/update.html", context={"form": form, "task": task}
        )


class ShowTaskView(BaseTaskView):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        return render(request, "tasks/show.html", context={"task": task})

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import ListView
from task_manager.tasks.models import Task
from task_manager.users.forms import CreateUserForm
from task_manager.users.models import User


class BaseUserView(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request, _("You are not logged in! Please sign in.")
            )
        return super().dispatch(request, *args, **kwargs)


class IndexUserView(ListView):
    model = User
    template_name = "users/index.html"
    context_object_name = "users"
    ordering = ["id"]


class CreateUserView(View):
    def get(self, request):
        return self._render_form(request, CreateUserForm())

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password1"])
            user.save()
            messages.success(request, _("User registered successfully"))
            return redirect("login")
        return self._render_form(request, form)

    def _render_form(self, request, form):
        return render(request, "users/create.html", context={"form": form})


class UpdateUserView(BaseUserView):
    def get(self, request, pk):
        user = self._get_user(pk)
        if isinstance(user, HttpResponseRedirect):
            return user
        form = CreateUserForm(instance=user)
        return self._render_form(request, form, user)

    def post(self, request, pk):
        user = self._get_user(pk)
        if isinstance(user, HttpResponseRedirect):
            return user
        form = CreateUserForm(request.POST, instance=user)
        if form.is_valid():
            updated_user = form.save(commit=False)
            updated_user.set_password(form.cleaned_data["password1"])
            updated_user.save()
            messages.success(request, _("User successfully changed."))
            return redirect("users:index")
        return self._render_form(request, form, user)

    def _get_user(self, user_id):
        user = get_object_or_404(User, id=user_id)
        auth_user_id = self.request.user.id

        if auth_user_id != int(user_id) and not self.request.user.is_superuser:
            messages.error(
                self.request,
                _("You do not have permission to change another user."),
            )
            return redirect("users:index")
        return user

    def _render_form(self, request, form, user):
        return render(
            request, "users/update.html", context={"form": form, "user": user}
        )


class DeleteUserView(BaseUserView):
    def get(self, request, pk):
        user = self._get_user(pk)
        if isinstance(user, HttpResponseRedirect):
            return user
        return render(request, "users/delete.html", context={"user": user})

    def post(self, request, pk):
        user = self._get_user(pk)
        if isinstance(user, HttpResponseRedirect):
            return user
        if Task.objects.filter(executor=user).exists():
            messages.error(
                request, _("Cannot delete user because it is in use")
            )
            return redirect("users:index")
        user.delete()
        messages.success(request, _("User successfully deleted"))
        return redirect("users:index")

    def _get_user(self, user_id):
        user = get_object_or_404(User, id=user_id)
        auth_user_id = self.request.user.id

        if auth_user_id != int(user_id) and not self.request.user.is_superuser:
            messages.error(
                self.request,
                _("You do not have permission to change another user."),
            )
            return redirect("users:index")
        return user

task_manager/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.views import View

from task_manager.forms import LoginForm


class IndexView(View):
    def get(self, request):
        return render(request, "index.html", context={})


class LoginView(View):
    def get(self, request):
        return self._render_form(request, LoginForm())

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                messages.success(request, _("You are login"))
                return redirect("index")
            form.add_error(
                None,
                _(
                    "Please enter a correct username and password. "
                    "Note that both fields may be case-sensitive."
                ),
            )
        return self._render_form(request, form)

    def _render_form(self, request, form):
        return render(request, "login.html", context={"form": form})


class LogoutView(View):
    def get(self, request):
        return redirect("index")

    def post(self, request):
        logout(request)
        messages.info(request, _("You are logout"))
        return redirect("index")

task_manager/templates/tasks/create.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
<main>
  <div class="container-md mt-3">
    <h1>{% trans "Create Task" %}</h1>

    <form id="task-create-form" method="post" action="{% url 'tasks:create' %}">
      {% csrf_token %}
      {% bootstrap_form form %}
      <!-- plain explicit submit button: текст совпадает с тем, что ищет тест -->
      <button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
    </form>
  </div>
</main>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Delete Task" %}</h1>

<p>{% blocktrans with task_name=object.name %}Are you sure you want to delete the task <strong>{{ task_name }}</strong>?{% endblocktrans %}</p>

<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
</form>
{% endblock %}

task_manager/templates/tasks/index.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
<main>
  <div class="container-md mt-3">
    <h1>{% trans "Tasks" %}</h1>
    <a href="{% url 'tasks:create' %}" class="btn btn-primary">{% trans "Create task" %}</a>

    <div class="container-md bg-body-tertiary mt-3 mb-3 border rounded-3">
        <div class="p-3">
            <form action="{% url 'tasks:index' %}" method="get">
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content=_("Show") %}
            </form>
        </div>
    </div>

    <table class="table table-striped mt-2" data-test="checks">
        <thead>
            <tr>
              <th>{% trans "ID" %}</th>
              <th>{% trans "Name" %}</th>
              <th>{% trans "Status" %}</th>
              <th>{% trans "Author" %}</th>
              <th>{% trans "Executor" %}</th>
              <th>{% trans "Create date" %}</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            {% if tasks %}
                {% for task in tasks %}
                <tr>
                    <td>{{ task.id }}</td>
                    <td><a href="{% url 'tasks:show' task.id %}">{{ task.name }}</a></td>
                    <td>{{ task.status }}</td>
                    <td>{{ task.author }}</td>
                    <td>{{ task.executor|default_if_none:"" }}</td>
                    <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
                    <td>
                        <a href="{% url 'tasks:update' task.id %}">{% trans "Edit" %}</a><br>
                        <a href="{% url 'tasks:delete' task.id %}">{% trans "Delete" %}</a>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
  </div>
</main>
{% endblock %}

task_manager/templates/tasks/show.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}
{% bootstrap_css %}

{% block content %}
<main>
  <div class="container-md mt-3">
    <h1>{% trans "View task" %}</h1>
    <div class="container bg-secondary text-white border rounded-3 rounded-bottom-0 py-2 px-3">
        <h2>{{ task.name }}</h2>
    </div>
    <div class="container bg-light border rounded-3 rounded-top-0 p-3">
        <p>{{ task.description }}</p>
        <hr>
        <div class="container">
            <div class="row p-1">
                <div class="col">{% trans "Author" %}</div>
                <div class="col">{{ task.author }}</div>
            </div>
            <div class="row p-1">
                <div class="col">{% trans "Executor" %}</div>
                <div class="col">{{ task.executor }}</div>
            </div>
            <div class="row p-1">
                <div class="col">{% trans "Status" %}</div>
                <div class="col">{{ task.status }}</div>
            </div>
            <div class="row p-1">
                <div class="col">{% trans "Date of creation" %}</div>
                <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
            </div>
            <div class="row p-1">
                <div class="col">
                    <h6>{% trans "Labels" %}:</h6>
                    <ul>
                        {% for label in task.labels.all %}
                            <li>{{ label.name }}</li>
                        {% endfor %}                
                    </ul>
                </div>
            </div>
            <div class="row p-1">
                <div class="col">
                    <a href="{% url 'tasks:update' task.id %}">{% trans "Edit" %}</a><br>
                    <a href="{% url 'tasks:delete' task.id %}">{% trans "Delete" %}</a>
                </div>
            </div>
        </div>
    </div>
</main> 
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}
{% bootstrap_css %}

{% block content %}
<main>
  <div class="container-md mt-3">
    <h1>{% trans "Changing a task" %}</h1>
    <form action="{% url 'tasks:update' task.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content=_("Change") %}
    </form>
  </div>
</main>
{% endblock %}